name: Appliance Firewall Settings
spec_endpoint: /networks/{networkId}/appliance/firewall/settings
rest_endpoint: /networks/%v/appliance/firewall/settings
put_create: true
no_delete: true
doc_category: Appliances
test_variables: [test_org, test_network]
attributes:
  - tf_name: network_id
    type: String
    id: true
    reference: true
    description: Network ID
    example: L_123456
    test_value: meraki_network.test.id
  - model_name: mode
    type: String
    data_path: [spoofingProtection, ipSourceGuard]
    description: Mode of protection
    example: block
    enum_values: [block, log]
    minimum_test_value: '"log"'
test_prerequisites: |
  data "meraki_organization" "test" {
    name = var.test_org
  }
  resource "meraki_network" "test" {
    organization_id = data.meraki_organization.test.id
    name            = var.test_network
    product_types   = ["switch", "wireless", "appliance"]
  }
