name: Camera Video Settings
spec_endpoint: /devices/{serial}/camera/video/settings
rest_endpoint: /devices/%v/camera/video/settings
put_create: true
no_delete: true
doc_category: Cameras
test_variables: [test_org, test_network, test_camera_1_serial]
attributes:
  - tf_name: serial
    type: String
    id: true
    reference: true
    description: Device serial
    example: 1234-ABCD-1234
    test_value: tolist(meraki_network_device_claim.test.serials)[0]
  - model_name: externalRtspEnabled
    type: Bool
    mandatory: true
    description: Boolean indicating if external rtsp stream is exposed
    example: "true"
    minimum_test_value: "false"
test_prerequisites: |
  data "meraki_organization" "test" {
    name = var.test_org
  }
  resource "meraki_network" "test" {
    organization_id = data.meraki_organization.test.id
    name            = var.test_network
    product_types   = ["switch", "wireless", "appliance", "sensor", "camera"]
  }
  resource "meraki_network_device_claim" "test" {
    network_id = meraki_network.test.id
    serials    = [var.test_camera_1_serial]
  }
