---
name: Network Settings
rest_endpoint: /networks/%v/settings
no_delete: true
put_create: true
doc_category: Networks
attributes:
  - tf_name: network_id
    type: String
    id: true
    reference: true
    description: Network ID
    example: L_123456
    test_value: meraki_network.test.id
  - model_name: localStatusPageEnabled
    type: Bool
    description: asdasdas
    example: false
    mandatory: true
  - model_name: remoteStatusPageEnabled
    type: Bool
    example: false
  - model_name: enabled
    data_path: [localStatusPage, authentication]
    type: Bool
    example: false
  - model_name: password
    data_path: [localStatusPage, authentication]
    type: String
    example: miles123
    write_only: true
  - model_name: enabled
    data_path: [namedVlans]
    type: Bool
    example: false
  - model_name: enabled
    data_path: [securePort]
    type: Bool
    example: false
  

test_prerequisites: |
  data "meraki_organization" "test" {
    name = "Dev"
  }
  resource "meraki_network" "test" {
    organization_id = data.meraki_organization.test.id
    name            = "Network1"
    product_types   = ["switch", "wireless"]
  }
