---
name: Network Settings
rest_endpoint: /networks/%v/settings
doc_category: Networks
no_delete: true
put_create: true
attributes:
- model_name: remoteStatusPageEnabled
  type: Bool
  description: Enables / disables access to the device status page (<a target='_blank'>http://[device's LAN IP])</a>. Optional. Can only be set if localStatusPageEnabled is set to true
  example: "true"
- model_name: enabled
  type: Bool
  data_path:
  - localStatusPage
  - authentication
  description: Enables / disables the authentication on Local Status page(s).
  example: "false"
- model_name: password
  type: String
  data_path:
  - localStatusPage
  - authentication
  description: The password used for Local Status Page(s). Set this to null to clear the password.
  example: miles123
  write_only: true
- model_name: enabled
  type: Bool
  data_path:
  - securePort
  description: Enables / disables SecureConnect on the network. Optional.
  example: "false"
- model_name: enabled
  type: Bool
  data_path:
  - namedVlans
  description: Enables / disables Named VLANs on the Network.
  example: "true"
- model_name: localStatusPageEnabled
  type: Bool
  description: Enables / disables the local device status pages (<a target='_blank' href='http://my.meraki.com/'>my.meraki.com, </a><a target='_blank' href='http://ap.meraki.com/'>ap.meraki.com, </a><a target='_blank' href='http://switch.meraki.com/'>switch.meraki.com, </a><a target='_blank' href='http://wired.meraki.com/'>wired.meraki.com</a>). Optional (defaults to false)
  example: "true"
  minimum_test_value: "true"
- tf_name: network_id
  type: String
  id: true
  reference: true
  description: Network ID
  example: L_123456
  test_value: meraki_network.test.id


test_prerequisites: |
  data "meraki_organization" "test" {
    name = "Dev"
  }
  resource "meraki_network" "test" {
    organization_id = data.meraki_organization.test.id
    name            = "Network1"
    product_types   = ["switch", "wireless"]
  }