---
name: Network Settings
rest_endpoint: /networks/%v/settings
no_delete: true
put_create: true
doc_category: Networks
get_from_all: true
attributes:
  - tf_name: network_id
    type: String
    reference: true
    description: Network ID
    example: L_123456
    test_value: meraki_network.test.id
  - model_name: localStatusPageEnabled
    type: Bool
    description: asdasdas
    example: false
test_prerequisites: |
  data "meraki_organization" "test" {
    name = "Dev"
  }
  resource "meraki_network" "test" {
    organization_id = data.meraki_organization.test.id
    name            = "Network1"
    product_types   = ["switch"]
  }
