# @endpoint: /organizations/{organizationId}/loginSecurity
name: Organization Login Security
rest_endpoint: /organizations/%v/loginSecurity
put_create: true
no_delete: true
doc_category: Organizations
test_tags: [ORGANIZATION]
attributes:
  - tf_name: organization_id
    type: String
    id: true
    reference: true
    description: Organization ID
    example: "123456"
    test_value: meraki_organization.test.id
  - model_name: accountLockoutAttempts
    type: Int64
    description: Number of consecutive failed login attempts after which users` accounts will be locked.
    example: "3"
    minimum_test_value: "5"
  - model_name: enforceAccountLockout
    type: Bool
    description: Boolean indicating whether users` Dashboard accounts will be locked out after a specified number of consecutive failed login attempts.
    example: "true"
  - model_name: enforceDifferentPasswords
    type: Bool
    description: Boolean indicating whether users, when setting a new password, are forced to choose a new password that is different from any past passwords.
    example: "true"
  - model_name: enforceIdleTimeout
    type: Bool
    description: Boolean indicating whether users will be logged out after being idle for the specified number of minutes.
    example: "true"
  - model_name: enforceLoginIpRanges
    type: Bool
    exclude_test: true
    description: Boolean indicating whether organization will restrict access to Dashboard (including the API) from certain IP addresses.
    example: "true"
  - model_name: enforcePasswordExpiration
    type: Bool
    description: Boolean indicating whether users are forced to change their password every X number of days.
    example: "true"
  - model_name: enforceStrongPasswords
    type: Bool
    description: 'Boolean indicating whether users will be forced to choose strong passwords for their accounts. Strong passwords are at least 8 characters that contain 3 of the following: number, uppercase letter, lowercase letter, and symbol'
    example: "true"
  - model_name: enforceTwoFactorAuth
    type: Bool
    description: Boolean indicating whether users in this organization will be required to use an extra verification code when logging in to Dashboard. This code will be sent to their mobile phone via SMS, or can be generated by the authenticator application.
    example: "true"
  - model_name: idleTimeoutMinutes
    type: Int64
    description: Number of minutes users can remain idle before being logged out of their accounts.
    example: "30"
  - model_name: numDifferentPasswords
    type: Int64
    description: Number of recent passwords that new password must be distinct from.
    example: "3"
  - model_name: passwordExpirationDays
    type: Int64
    description: Number of days after which users will be forced to change their password.
    example: "90"
  - model_name: enabled
    type: Bool
    data_path: [apiAuthentication, ipRestrictionsForKeys]
    exclude_test: true
    description: Boolean indicating whether the organization will restrict API key (not Dashboard GUI) usage to a specific list of IP addresses or CIDR ranges.
    example: "true"
  - model_name: ranges
    type: List
    element_type: String
    data_path: [apiAuthentication, ipRestrictionsForKeys]
    exclude_test: true
    description: List of acceptable IP ranges. Entries can be single IP addresses, IP address ranges, and CIDR subnets.
    example: 192.195.83.1
  - model_name: loginIpRanges
    type: List
    element_type: String
    exclude_test: true
    description: List of acceptable IP ranges. Entries can be single IP addresses, IP address ranges, and CIDR subnets.
    example: 192.195.83.1
test_prerequisites: |
  resource "meraki_organization" "test" {
    name = "TF-Test"
  }
