name: Switch Settings
spec_endpoint: /networks/{networkId}/switch/settings
rest_endpoint: /networks/%v/switch/settings
put_create: true
no_delete: true
doc_category: Switches
test_variables: [test_org, test_network]
attributes:
  - tf_name: network_id
    type: String
    id: true
    reference: true
    description: Network ID
    example: L_123456
    test_value: meraki_network.test.id
  - model_name: useCombinedPower
    type: Bool
    description: The use Combined Power as the default behavior of secondary power supplies on supported devices.
    example: "false"
  - model_name: vlan
    type: Int64
    description: Management VLAN
    example: "1"
    minimum_test_value: "1"
  - model_name: enabled
    type: Bool
    data_path: [macBlocklist]
    description: Enable MAC blocklist
    example: "true"
  - model_name: enabled
    type: Bool
    data_path: [uplinkClientSampling]
    description: Enable uplink client sampling
    example: "false"
  - model_name: powerExceptions
    type: List
    exclude_test: true
    description: Exceptions on a per switch basis to 'useCombinedPower'
    attributes:
      - model_name: powerType
        type: String
        mandatory: true
        description: Per switch exception (combined, redundant, useNetworkSetting)
        example: useNetworkSetting
        enum_values: [combined, redundant, useNetworkSetting]
      - model_name: serial
        type: String
        id: true
        mandatory: true
        description: Serial number of the switch
        example: Q234-ABCD-5678
test_prerequisites: |
  data "meraki_organization" "test" {
    name = var.test_org
  }
  resource "meraki_network" "test" {
    organization_id = data.meraki_organization.test.id
    name            = var.test_network
    product_types   = ["switch", "wireless"]
  }
