name: Switch Settings
rest_endpoint: /networks/%v/switch/settings
put_create: true
no_delete: true
doc_category: Switches
attributes:
  - tf_name: network_id
    type: String
    id: true
    reference: true
    description: Network ID
    example: L_123456
    test_value: meraki_network.test.id
  - model_name: useCombinedPower
    type: Bool
    description: The use Combined Power as the default behavior of secondary power supplies on supported devices.
    example: false
  - model_name: vlan
    type: Int64
    description: Management VLAN
    example: 1
    minimum_test_value: 1
  - model_name: enabled
    type: Bool
    data_path: [macBlocklist]
    description: Enable MAC blocklist
    example: true
  - model_name: enabled
    type: Bool
    data_path: [uplinkClientSampling]
    description: Enable uplink client sampling
    example: false
  - model_name: powerExceptions
    type: List
    description: Exceptions on a per switch basis to 'useCombinedPower'
    exclude_test: true
    attributes:
      - model_name: powerType
        type: String
        mandatory: true
        description: Per switch exception (combined, redundant, useNetworkSetting)
        enum_values: [combined, redundant, useNetworkSetting]
        example: useNetworkSetting
      - model_name: serial
        type: String
        mandatory: true
        id: true
        description: Serial number of the switch
        example: Q234-ABCD-5678
test_prerequisites: |
  data "meraki_organization" "test" {
    name = "Dev"
  }
  resource "meraki_network" "test" {
    organization_id = data.meraki_organization.test.id
    name            = "Network1"
    product_types   = ["switch", "wireless"]
  }
