name: Wireless Air Marshal Settings
spec_endpoint: /networks/{networkId}/wireless/airMarshal/settings
rest_endpoint: /networks/%v/wireless/airMarshal/settings
put_create: true
no_delete: true
doc_category: Wireless
skip_minimum_test: true
test_variables: [test_org, test_network]
attributes:
  - tf_name: network_id
    type: String
    id: true
    reference: true
    description: Network ID
    example: L_123456
    test_value: meraki_network.test.id
  - model_name: defaultPolicy
    type: String
    mandatory: true
    description: Allows clients to access rogue networks. Blocked by default.
    example: allow
    enum_values: [allow, block]
test_prerequisites: |
  data "meraki_organization" "test" {
    name = var.test_org
  }
  resource "meraki_network" "test" {
    organization_id = data.meraki_organization.test.id
    name            = var.test_network
    product_types   = ["switch", "wireless"]
  }
