resource "meraki_switch_port" "example" {
  serial                      = "1234-ABCD-1234"
  port_id                     = "1"
  access_policy_number        = 2
  access_policy_type          = "Sticky MAC allow list"
  adaptive_policy_group_id    = "123"
  allowed_vlans               = "1,3,5-10"
  dai_trusted                 = false
  enabled                     = true
  flexible_stacking_enabled   = true
  isolation_enabled           = false
  link_negotiation            = "Auto negotiate"
  name                        = "My switch port"
  peer_sgt_capable            = false
  poe_enabled                 = true
  port_schedule_id            = "1234"
  rstp_enabled                = true
  sticky_mac_allow_list_limit = 5
  storm_control_enabled       = true
  stp_guard                   = "disabled"
  type                        = "access"
  udld                        = "Alert only"
  vlan                        = 10
  voice_vlan                  = 20
  dot3az_enabled              = false
  profile_enabled             = false
  profile_id                  = "1284392014819"
  profile_iname               = "iname"
  mac_allow_list              = ["34:56:fe:ce:8e:a0"]
  sticky_mac_allow_list       = ["34:56:fe:ce:8e:b0"]
  tags                        = ["tag1"]
}
