name: Update UserAgent with Release Version

on:
  push:
    branches: [ main, develop ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-useragent:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Extract version from CHANGELOG
        id: extract-version
        run: |
          # Extract the latest version from CHANGELOG.md
          VERSION=$(grep -E '^## [0-9]+\.[0-9]+\.[0-9]+' CHANGELOG.md | head -1 | sed 's/^## //' | sed 's/ (unreleased)//')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Extracted version: $VERSION"

      - name: Update UserAgent
        run: |
          python3 scripts/update-useragent-python.py ${{ steps.extract-version.outputs.version }}

      - name: Check for changes
        id: check-changes
        run: |
          if git diff --quiet; then
            echo "changes=false" >> $GITHUB_OUTPUT
            echo "No changes detected"
          else
            echo "changes=true" >> $GITHUB_OUTPUT
            echo "Changes detected"
            git diff
          fi

      - name: Commit and push changes
        if: steps.check-changes.outputs.changes == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add internal/provider/provider.go
          git commit -m "Update UserAgent to version ${{ steps.extract-version.outputs.version }}"
          git push