# Workflow to automatically update UserAgent with latest version from changelog
name: Update UserAgent

# This workflow can be triggered manually or on schedule
on:
  workflow_dispatch:
  schedule:
    # Run daily at 9 AM UTC to check for new versions
    - cron: '0 9 * * *'
  push:
    paths:
      - 'CHANGELOG.md'
      - 'docs/guides/changelog.md'

# Only needs read permissions for this workflow
permissions:
  contents: read

jobs:
  update-useragent:
    name: Update UserAgent
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Update UserAgent with latest version
        run: |
          echo "Updating UserAgent with latest version from changelog..."
          python3 scripts/update-useragent-python.py
          
          # Check if there are changes
          if git diff --quiet; then
            echo "No changes needed - UserAgent is already up to date"
          else
            echo "Changes detected:"
            git diff
            
            # Commit and push changes
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add internal/provider/provider.go
            git commit -m "chore: update UserAgent to latest version from changelog"
            git push
          fi
